version: '3.9'

services:
  app:
    container_name: news-app
    build: 
      context: .
      target: back
    ports:
      - 8001:8000
    environment:
      - PYTHON_PATH=
    networks:
      es-network:
        aliases:
            - news
    volumes:
      - .:/st
    depends_on:
      - elasticsearch
    command: "python app/main.py"

  front:
    image: nginx
    ports:
      - "80:80"

    volumes:
      - ./front/:/usr/share/nginx/html

  elasticsearch:
    image: elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - MAX_LOCKED_MEMORY=unlimited
    volumes:
      - ./es_data_volume:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    ports:
      - 9203:9200
    networks:
      es-network:
        aliases:
          - elastic-news
  
  kibana:
    image: kibana:7.17.20
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS = http://elasticsearch:9203
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      es-network:
        aliases:
          - elastic-kibana
        

networks:
  es-network:
    name: es-network